/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package auto.ria.core;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CarAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7184958919675402371L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CarAvro\",\"namespace\":\"auto.ria.core\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"addDate\",\"type\":\"string\"},{\"name\":\"brandId\",\"type\":\"int\"},{\"name\":\"brand\",\"type\":\"string\"},{\"name\":\"modelId\",\"type\":\"int\"},{\"name\":\"model\",\"type\":\"string\"},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"desc\",\"type\":[\"string\",\"null\"]},{\"name\":\"priceUsd\",\"type\":\"int\"},{\"name\":\"year\",\"type\":\"int\"},{\"name\":\"link\",\"type\":\"string\"},{\"name\":\"fuelId\",\"type\":\"int\"},{\"name\":\"fuel\",\"type\":\"string\"},{\"name\":\"gearBoxId\",\"type\":[\"int\",\"null\"]},{\"name\":\"gearBox\",\"type\":[\"string\",\"null\"]},{\"name\":\"driveId\",\"type\":[\"int\",\"null\"]},{\"name\":\"drive\",\"type\":[\"string\",\"null\"]},{\"name\":\"location\",\"type\":\"string\"},{\"name\":\"region\",\"type\":\"string\"},{\"name\":\"race\",\"type\":[\"string\",\"null\"]},{\"name\":\"raceInt\",\"type\":[\"int\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CarAvro> ENCODER =
      new BinaryMessageEncoder<CarAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CarAvro> DECODER =
      new BinaryMessageDecoder<CarAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CarAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CarAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CarAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CarAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CarAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CarAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CarAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CarAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence addDate;
  @Deprecated public int brandId;
  @Deprecated public java.lang.CharSequence brand;
  @Deprecated public int modelId;
  @Deprecated public java.lang.CharSequence model;
  @Deprecated public java.lang.CharSequence title;
  @Deprecated public java.lang.CharSequence desc;
  @Deprecated public int priceUsd;
  @Deprecated public int year;
  @Deprecated public java.lang.CharSequence link;
  @Deprecated public int fuelId;
  @Deprecated public java.lang.CharSequence fuel;
  @Deprecated public java.lang.Integer gearBoxId;
  @Deprecated public java.lang.CharSequence gearBox;
  @Deprecated public java.lang.Integer driveId;
  @Deprecated public java.lang.CharSequence drive;
  @Deprecated public java.lang.CharSequence location;
  @Deprecated public java.lang.CharSequence region;
  @Deprecated public java.lang.CharSequence race;
  @Deprecated public java.lang.Integer raceInt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CarAvro() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param addDate The new value for addDate
   * @param brandId The new value for brandId
   * @param brand The new value for brand
   * @param modelId The new value for modelId
   * @param model The new value for model
   * @param title The new value for title
   * @param desc The new value for desc
   * @param priceUsd The new value for priceUsd
   * @param year The new value for year
   * @param link The new value for link
   * @param fuelId The new value for fuelId
   * @param fuel The new value for fuel
   * @param gearBoxId The new value for gearBoxId
   * @param gearBox The new value for gearBox
   * @param driveId The new value for driveId
   * @param drive The new value for drive
   * @param location The new value for location
   * @param region The new value for region
   * @param race The new value for race
   * @param raceInt The new value for raceInt
   */
  public CarAvro(java.lang.CharSequence id, java.lang.CharSequence addDate, java.lang.Integer brandId, java.lang.CharSequence brand, java.lang.Integer modelId, java.lang.CharSequence model, java.lang.CharSequence title, java.lang.CharSequence desc, java.lang.Integer priceUsd, java.lang.Integer year, java.lang.CharSequence link, java.lang.Integer fuelId, java.lang.CharSequence fuel, java.lang.Integer gearBoxId, java.lang.CharSequence gearBox, java.lang.Integer driveId, java.lang.CharSequence drive, java.lang.CharSequence location, java.lang.CharSequence region, java.lang.CharSequence race, java.lang.Integer raceInt) {
    this.id = id;
    this.addDate = addDate;
    this.brandId = brandId;
    this.brand = brand;
    this.modelId = modelId;
    this.model = model;
    this.title = title;
    this.desc = desc;
    this.priceUsd = priceUsd;
    this.year = year;
    this.link = link;
    this.fuelId = fuelId;
    this.fuel = fuel;
    this.gearBoxId = gearBoxId;
    this.gearBox = gearBox;
    this.driveId = driveId;
    this.drive = drive;
    this.location = location;
    this.region = region;
    this.race = race;
    this.raceInt = raceInt;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return addDate;
    case 2: return brandId;
    case 3: return brand;
    case 4: return modelId;
    case 5: return model;
    case 6: return title;
    case 7: return desc;
    case 8: return priceUsd;
    case 9: return year;
    case 10: return link;
    case 11: return fuelId;
    case 12: return fuel;
    case 13: return gearBoxId;
    case 14: return gearBox;
    case 15: return driveId;
    case 16: return drive;
    case 17: return location;
    case 18: return region;
    case 19: return race;
    case 20: return raceInt;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: addDate = (java.lang.CharSequence)value$; break;
    case 2: brandId = (java.lang.Integer)value$; break;
    case 3: brand = (java.lang.CharSequence)value$; break;
    case 4: modelId = (java.lang.Integer)value$; break;
    case 5: model = (java.lang.CharSequence)value$; break;
    case 6: title = (java.lang.CharSequence)value$; break;
    case 7: desc = (java.lang.CharSequence)value$; break;
    case 8: priceUsd = (java.lang.Integer)value$; break;
    case 9: year = (java.lang.Integer)value$; break;
    case 10: link = (java.lang.CharSequence)value$; break;
    case 11: fuelId = (java.lang.Integer)value$; break;
    case 12: fuel = (java.lang.CharSequence)value$; break;
    case 13: gearBoxId = (java.lang.Integer)value$; break;
    case 14: gearBox = (java.lang.CharSequence)value$; break;
    case 15: driveId = (java.lang.Integer)value$; break;
    case 16: drive = (java.lang.CharSequence)value$; break;
    case 17: location = (java.lang.CharSequence)value$; break;
    case 18: region = (java.lang.CharSequence)value$; break;
    case 19: race = (java.lang.CharSequence)value$; break;
    case 20: raceInt = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'addDate' field.
   * @return The value of the 'addDate' field.
   */
  public java.lang.CharSequence getAddDate() {
    return addDate;
  }


  /**
   * Sets the value of the 'addDate' field.
   * @param value the value to set.
   */
  public void setAddDate(java.lang.CharSequence value) {
    this.addDate = value;
  }

  /**
   * Gets the value of the 'brandId' field.
   * @return The value of the 'brandId' field.
   */
  public int getBrandId() {
    return brandId;
  }


  /**
   * Sets the value of the 'brandId' field.
   * @param value the value to set.
   */
  public void setBrandId(int value) {
    this.brandId = value;
  }

  /**
   * Gets the value of the 'brand' field.
   * @return The value of the 'brand' field.
   */
  public java.lang.CharSequence getBrand() {
    return brand;
  }


  /**
   * Sets the value of the 'brand' field.
   * @param value the value to set.
   */
  public void setBrand(java.lang.CharSequence value) {
    this.brand = value;
  }

  /**
   * Gets the value of the 'modelId' field.
   * @return The value of the 'modelId' field.
   */
  public int getModelId() {
    return modelId;
  }


  /**
   * Sets the value of the 'modelId' field.
   * @param value the value to set.
   */
  public void setModelId(int value) {
    this.modelId = value;
  }

  /**
   * Gets the value of the 'model' field.
   * @return The value of the 'model' field.
   */
  public java.lang.CharSequence getModel() {
    return model;
  }


  /**
   * Sets the value of the 'model' field.
   * @param value the value to set.
   */
  public void setModel(java.lang.CharSequence value) {
    this.model = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'desc' field.
   * @return The value of the 'desc' field.
   */
  public java.lang.CharSequence getDesc() {
    return desc;
  }


  /**
   * Sets the value of the 'desc' field.
   * @param value the value to set.
   */
  public void setDesc(java.lang.CharSequence value) {
    this.desc = value;
  }

  /**
   * Gets the value of the 'priceUsd' field.
   * @return The value of the 'priceUsd' field.
   */
  public int getPriceUsd() {
    return priceUsd;
  }


  /**
   * Sets the value of the 'priceUsd' field.
   * @param value the value to set.
   */
  public void setPriceUsd(int value) {
    this.priceUsd = value;
  }

  /**
   * Gets the value of the 'year' field.
   * @return The value of the 'year' field.
   */
  public int getYear() {
    return year;
  }


  /**
   * Sets the value of the 'year' field.
   * @param value the value to set.
   */
  public void setYear(int value) {
    this.year = value;
  }

  /**
   * Gets the value of the 'link' field.
   * @return The value of the 'link' field.
   */
  public java.lang.CharSequence getLink() {
    return link;
  }


  /**
   * Sets the value of the 'link' field.
   * @param value the value to set.
   */
  public void setLink(java.lang.CharSequence value) {
    this.link = value;
  }

  /**
   * Gets the value of the 'fuelId' field.
   * @return The value of the 'fuelId' field.
   */
  public int getFuelId() {
    return fuelId;
  }


  /**
   * Sets the value of the 'fuelId' field.
   * @param value the value to set.
   */
  public void setFuelId(int value) {
    this.fuelId = value;
  }

  /**
   * Gets the value of the 'fuel' field.
   * @return The value of the 'fuel' field.
   */
  public java.lang.CharSequence getFuel() {
    return fuel;
  }


  /**
   * Sets the value of the 'fuel' field.
   * @param value the value to set.
   */
  public void setFuel(java.lang.CharSequence value) {
    this.fuel = value;
  }

  /**
   * Gets the value of the 'gearBoxId' field.
   * @return The value of the 'gearBoxId' field.
   */
  public java.lang.Integer getGearBoxId() {
    return gearBoxId;
  }


  /**
   * Sets the value of the 'gearBoxId' field.
   * @param value the value to set.
   */
  public void setGearBoxId(java.lang.Integer value) {
    this.gearBoxId = value;
  }

  /**
   * Gets the value of the 'gearBox' field.
   * @return The value of the 'gearBox' field.
   */
  public java.lang.CharSequence getGearBox() {
    return gearBox;
  }


  /**
   * Sets the value of the 'gearBox' field.
   * @param value the value to set.
   */
  public void setGearBox(java.lang.CharSequence value) {
    this.gearBox = value;
  }

  /**
   * Gets the value of the 'driveId' field.
   * @return The value of the 'driveId' field.
   */
  public java.lang.Integer getDriveId() {
    return driveId;
  }


  /**
   * Sets the value of the 'driveId' field.
   * @param value the value to set.
   */
  public void setDriveId(java.lang.Integer value) {
    this.driveId = value;
  }

  /**
   * Gets the value of the 'drive' field.
   * @return The value of the 'drive' field.
   */
  public java.lang.CharSequence getDrive() {
    return drive;
  }


  /**
   * Sets the value of the 'drive' field.
   * @param value the value to set.
   */
  public void setDrive(java.lang.CharSequence value) {
    this.drive = value;
  }

  /**
   * Gets the value of the 'location' field.
   * @return The value of the 'location' field.
   */
  public java.lang.CharSequence getLocation() {
    return location;
  }


  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(java.lang.CharSequence value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'region' field.
   * @return The value of the 'region' field.
   */
  public java.lang.CharSequence getRegion() {
    return region;
  }


  /**
   * Sets the value of the 'region' field.
   * @param value the value to set.
   */
  public void setRegion(java.lang.CharSequence value) {
    this.region = value;
  }

  /**
   * Gets the value of the 'race' field.
   * @return The value of the 'race' field.
   */
  public java.lang.CharSequence getRace() {
    return race;
  }


  /**
   * Sets the value of the 'race' field.
   * @param value the value to set.
   */
  public void setRace(java.lang.CharSequence value) {
    this.race = value;
  }

  /**
   * Gets the value of the 'raceInt' field.
   * @return The value of the 'raceInt' field.
   */
  public java.lang.Integer getRaceInt() {
    return raceInt;
  }


  /**
   * Sets the value of the 'raceInt' field.
   * @param value the value to set.
   */
  public void setRaceInt(java.lang.Integer value) {
    this.raceInt = value;
  }

  /**
   * Creates a new CarAvro RecordBuilder.
   * @return A new CarAvro RecordBuilder
   */
  public static auto.ria.core.CarAvro.Builder newBuilder() {
    return new auto.ria.core.CarAvro.Builder();
  }

  /**
   * Creates a new CarAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CarAvro RecordBuilder
   */
  public static auto.ria.core.CarAvro.Builder newBuilder(auto.ria.core.CarAvro.Builder other) {
    if (other == null) {
      return new auto.ria.core.CarAvro.Builder();
    } else {
      return new auto.ria.core.CarAvro.Builder(other);
    }
  }

  /**
   * Creates a new CarAvro RecordBuilder by copying an existing CarAvro instance.
   * @param other The existing instance to copy.
   * @return A new CarAvro RecordBuilder
   */
  public static auto.ria.core.CarAvro.Builder newBuilder(auto.ria.core.CarAvro other) {
    if (other == null) {
      return new auto.ria.core.CarAvro.Builder();
    } else {
      return new auto.ria.core.CarAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for CarAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CarAvro>
    implements org.apache.avro.data.RecordBuilder<CarAvro> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence addDate;
    private int brandId;
    private java.lang.CharSequence brand;
    private int modelId;
    private java.lang.CharSequence model;
    private java.lang.CharSequence title;
    private java.lang.CharSequence desc;
    private int priceUsd;
    private int year;
    private java.lang.CharSequence link;
    private int fuelId;
    private java.lang.CharSequence fuel;
    private java.lang.Integer gearBoxId;
    private java.lang.CharSequence gearBox;
    private java.lang.Integer driveId;
    private java.lang.CharSequence drive;
    private java.lang.CharSequence location;
    private java.lang.CharSequence region;
    private java.lang.CharSequence race;
    private java.lang.Integer raceInt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(auto.ria.core.CarAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.addDate)) {
        this.addDate = data().deepCopy(fields()[1].schema(), other.addDate);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.brandId)) {
        this.brandId = data().deepCopy(fields()[2].schema(), other.brandId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.brand)) {
        this.brand = data().deepCopy(fields()[3].schema(), other.brand);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.modelId)) {
        this.modelId = data().deepCopy(fields()[4].schema(), other.modelId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.model)) {
        this.model = data().deepCopy(fields()[5].schema(), other.model);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.title)) {
        this.title = data().deepCopy(fields()[6].schema(), other.title);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.desc)) {
        this.desc = data().deepCopy(fields()[7].schema(), other.desc);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.priceUsd)) {
        this.priceUsd = data().deepCopy(fields()[8].schema(), other.priceUsd);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.year)) {
        this.year = data().deepCopy(fields()[9].schema(), other.year);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.link)) {
        this.link = data().deepCopy(fields()[10].schema(), other.link);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.fuelId)) {
        this.fuelId = data().deepCopy(fields()[11].schema(), other.fuelId);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.fuel)) {
        this.fuel = data().deepCopy(fields()[12].schema(), other.fuel);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.gearBoxId)) {
        this.gearBoxId = data().deepCopy(fields()[13].schema(), other.gearBoxId);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.gearBox)) {
        this.gearBox = data().deepCopy(fields()[14].schema(), other.gearBox);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.driveId)) {
        this.driveId = data().deepCopy(fields()[15].schema(), other.driveId);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.drive)) {
        this.drive = data().deepCopy(fields()[16].schema(), other.drive);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
      if (isValidValue(fields()[17], other.location)) {
        this.location = data().deepCopy(fields()[17].schema(), other.location);
        fieldSetFlags()[17] = other.fieldSetFlags()[17];
      }
      if (isValidValue(fields()[18], other.region)) {
        this.region = data().deepCopy(fields()[18].schema(), other.region);
        fieldSetFlags()[18] = other.fieldSetFlags()[18];
      }
      if (isValidValue(fields()[19], other.race)) {
        this.race = data().deepCopy(fields()[19].schema(), other.race);
        fieldSetFlags()[19] = other.fieldSetFlags()[19];
      }
      if (isValidValue(fields()[20], other.raceInt)) {
        this.raceInt = data().deepCopy(fields()[20].schema(), other.raceInt);
        fieldSetFlags()[20] = other.fieldSetFlags()[20];
      }
    }

    /**
     * Creates a Builder by copying an existing CarAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(auto.ria.core.CarAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.addDate)) {
        this.addDate = data().deepCopy(fields()[1].schema(), other.addDate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.brandId)) {
        this.brandId = data().deepCopy(fields()[2].schema(), other.brandId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.brand)) {
        this.brand = data().deepCopy(fields()[3].schema(), other.brand);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.modelId)) {
        this.modelId = data().deepCopy(fields()[4].schema(), other.modelId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.model)) {
        this.model = data().deepCopy(fields()[5].schema(), other.model);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.title)) {
        this.title = data().deepCopy(fields()[6].schema(), other.title);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.desc)) {
        this.desc = data().deepCopy(fields()[7].schema(), other.desc);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.priceUsd)) {
        this.priceUsd = data().deepCopy(fields()[8].schema(), other.priceUsd);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.year)) {
        this.year = data().deepCopy(fields()[9].schema(), other.year);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.link)) {
        this.link = data().deepCopy(fields()[10].schema(), other.link);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.fuelId)) {
        this.fuelId = data().deepCopy(fields()[11].schema(), other.fuelId);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.fuel)) {
        this.fuel = data().deepCopy(fields()[12].schema(), other.fuel);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.gearBoxId)) {
        this.gearBoxId = data().deepCopy(fields()[13].schema(), other.gearBoxId);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.gearBox)) {
        this.gearBox = data().deepCopy(fields()[14].schema(), other.gearBox);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.driveId)) {
        this.driveId = data().deepCopy(fields()[15].schema(), other.driveId);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.drive)) {
        this.drive = data().deepCopy(fields()[16].schema(), other.drive);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.location)) {
        this.location = data().deepCopy(fields()[17].schema(), other.location);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.region)) {
        this.region = data().deepCopy(fields()[18].schema(), other.region);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.race)) {
        this.race = data().deepCopy(fields()[19].schema(), other.race);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.raceInt)) {
        this.raceInt = data().deepCopy(fields()[20].schema(), other.raceInt);
        fieldSetFlags()[20] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'addDate' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddDate() {
      return addDate;
    }


    /**
      * Sets the value of the 'addDate' field.
      * @param value The value of 'addDate'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setAddDate(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.addDate = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'addDate' field has been set.
      * @return True if the 'addDate' field has been set, false otherwise.
      */
    public boolean hasAddDate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'addDate' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearAddDate() {
      addDate = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'brandId' field.
      * @return The value.
      */
    public int getBrandId() {
      return brandId;
    }


    /**
      * Sets the value of the 'brandId' field.
      * @param value The value of 'brandId'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setBrandId(int value) {
      validate(fields()[2], value);
      this.brandId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'brandId' field has been set.
      * @return True if the 'brandId' field has been set, false otherwise.
      */
    public boolean hasBrandId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'brandId' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearBrandId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'brand' field.
      * @return The value.
      */
    public java.lang.CharSequence getBrand() {
      return brand;
    }


    /**
      * Sets the value of the 'brand' field.
      * @param value The value of 'brand'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setBrand(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.brand = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'brand' field has been set.
      * @return True if the 'brand' field has been set, false otherwise.
      */
    public boolean hasBrand() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'brand' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearBrand() {
      brand = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'modelId' field.
      * @return The value.
      */
    public int getModelId() {
      return modelId;
    }


    /**
      * Sets the value of the 'modelId' field.
      * @param value The value of 'modelId'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setModelId(int value) {
      validate(fields()[4], value);
      this.modelId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'modelId' field has been set.
      * @return True if the 'modelId' field has been set, false otherwise.
      */
    public boolean hasModelId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'modelId' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearModelId() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'model' field.
      * @return The value.
      */
    public java.lang.CharSequence getModel() {
      return model;
    }


    /**
      * Sets the value of the 'model' field.
      * @param value The value of 'model'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setModel(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.model = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'model' field has been set.
      * @return True if the 'model' field has been set, false otherwise.
      */
    public boolean hasModel() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'model' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearModel() {
      model = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.title = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearTitle() {
      title = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'desc' field.
      * @return The value.
      */
    public java.lang.CharSequence getDesc() {
      return desc;
    }


    /**
      * Sets the value of the 'desc' field.
      * @param value The value of 'desc'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setDesc(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.desc = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'desc' field has been set.
      * @return True if the 'desc' field has been set, false otherwise.
      */
    public boolean hasDesc() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'desc' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearDesc() {
      desc = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'priceUsd' field.
      * @return The value.
      */
    public int getPriceUsd() {
      return priceUsd;
    }


    /**
      * Sets the value of the 'priceUsd' field.
      * @param value The value of 'priceUsd'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setPriceUsd(int value) {
      validate(fields()[8], value);
      this.priceUsd = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'priceUsd' field has been set.
      * @return True if the 'priceUsd' field has been set, false otherwise.
      */
    public boolean hasPriceUsd() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'priceUsd' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearPriceUsd() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'year' field.
      * @return The value.
      */
    public int getYear() {
      return year;
    }


    /**
      * Sets the value of the 'year' field.
      * @param value The value of 'year'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setYear(int value) {
      validate(fields()[9], value);
      this.year = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'year' field has been set.
      * @return True if the 'year' field has been set, false otherwise.
      */
    public boolean hasYear() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'year' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearYear() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'link' field.
      * @return The value.
      */
    public java.lang.CharSequence getLink() {
      return link;
    }


    /**
      * Sets the value of the 'link' field.
      * @param value The value of 'link'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setLink(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.link = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'link' field has been set.
      * @return True if the 'link' field has been set, false otherwise.
      */
    public boolean hasLink() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'link' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearLink() {
      link = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'fuelId' field.
      * @return The value.
      */
    public int getFuelId() {
      return fuelId;
    }


    /**
      * Sets the value of the 'fuelId' field.
      * @param value The value of 'fuelId'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setFuelId(int value) {
      validate(fields()[11], value);
      this.fuelId = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'fuelId' field has been set.
      * @return True if the 'fuelId' field has been set, false otherwise.
      */
    public boolean hasFuelId() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'fuelId' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearFuelId() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'fuel' field.
      * @return The value.
      */
    public java.lang.CharSequence getFuel() {
      return fuel;
    }


    /**
      * Sets the value of the 'fuel' field.
      * @param value The value of 'fuel'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setFuel(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.fuel = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'fuel' field has been set.
      * @return True if the 'fuel' field has been set, false otherwise.
      */
    public boolean hasFuel() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'fuel' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearFuel() {
      fuel = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'gearBoxId' field.
      * @return The value.
      */
    public java.lang.Integer getGearBoxId() {
      return gearBoxId;
    }


    /**
      * Sets the value of the 'gearBoxId' field.
      * @param value The value of 'gearBoxId'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setGearBoxId(java.lang.Integer value) {
      validate(fields()[13], value);
      this.gearBoxId = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'gearBoxId' field has been set.
      * @return True if the 'gearBoxId' field has been set, false otherwise.
      */
    public boolean hasGearBoxId() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'gearBoxId' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearGearBoxId() {
      gearBoxId = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'gearBox' field.
      * @return The value.
      */
    public java.lang.CharSequence getGearBox() {
      return gearBox;
    }


    /**
      * Sets the value of the 'gearBox' field.
      * @param value The value of 'gearBox'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setGearBox(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.gearBox = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'gearBox' field has been set.
      * @return True if the 'gearBox' field has been set, false otherwise.
      */
    public boolean hasGearBox() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'gearBox' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearGearBox() {
      gearBox = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'driveId' field.
      * @return The value.
      */
    public java.lang.Integer getDriveId() {
      return driveId;
    }


    /**
      * Sets the value of the 'driveId' field.
      * @param value The value of 'driveId'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setDriveId(java.lang.Integer value) {
      validate(fields()[15], value);
      this.driveId = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'driveId' field has been set.
      * @return True if the 'driveId' field has been set, false otherwise.
      */
    public boolean hasDriveId() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'driveId' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearDriveId() {
      driveId = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'drive' field.
      * @return The value.
      */
    public java.lang.CharSequence getDrive() {
      return drive;
    }


    /**
      * Sets the value of the 'drive' field.
      * @param value The value of 'drive'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setDrive(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.drive = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'drive' field has been set.
      * @return True if the 'drive' field has been set, false otherwise.
      */
    public boolean hasDrive() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'drive' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearDrive() {
      drive = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'location' field.
      * @return The value.
      */
    public java.lang.CharSequence getLocation() {
      return location;
    }


    /**
      * Sets the value of the 'location' field.
      * @param value The value of 'location'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setLocation(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.location = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'location' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearLocation() {
      location = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'region' field.
      * @return The value.
      */
    public java.lang.CharSequence getRegion() {
      return region;
    }


    /**
      * Sets the value of the 'region' field.
      * @param value The value of 'region'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setRegion(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.region = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'region' field has been set.
      * @return True if the 'region' field has been set, false otherwise.
      */
    public boolean hasRegion() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'region' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearRegion() {
      region = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'race' field.
      * @return The value.
      */
    public java.lang.CharSequence getRace() {
      return race;
    }


    /**
      * Sets the value of the 'race' field.
      * @param value The value of 'race'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setRace(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.race = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'race' field has been set.
      * @return True if the 'race' field has been set, false otherwise.
      */
    public boolean hasRace() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'race' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearRace() {
      race = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'raceInt' field.
      * @return The value.
      */
    public java.lang.Integer getRaceInt() {
      return raceInt;
    }


    /**
      * Sets the value of the 'raceInt' field.
      * @param value The value of 'raceInt'.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder setRaceInt(java.lang.Integer value) {
      validate(fields()[20], value);
      this.raceInt = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'raceInt' field has been set.
      * @return True if the 'raceInt' field has been set, false otherwise.
      */
    public boolean hasRaceInt() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'raceInt' field.
      * @return This builder.
      */
    public auto.ria.core.CarAvro.Builder clearRaceInt() {
      raceInt = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CarAvro build() {
      try {
        CarAvro record = new CarAvro();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.addDate = fieldSetFlags()[1] ? this.addDate : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.brandId = fieldSetFlags()[2] ? this.brandId : (java.lang.Integer) defaultValue(fields()[2]);
        record.brand = fieldSetFlags()[3] ? this.brand : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.modelId = fieldSetFlags()[4] ? this.modelId : (java.lang.Integer) defaultValue(fields()[4]);
        record.model = fieldSetFlags()[5] ? this.model : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.title = fieldSetFlags()[6] ? this.title : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.desc = fieldSetFlags()[7] ? this.desc : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.priceUsd = fieldSetFlags()[8] ? this.priceUsd : (java.lang.Integer) defaultValue(fields()[8]);
        record.year = fieldSetFlags()[9] ? this.year : (java.lang.Integer) defaultValue(fields()[9]);
        record.link = fieldSetFlags()[10] ? this.link : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.fuelId = fieldSetFlags()[11] ? this.fuelId : (java.lang.Integer) defaultValue(fields()[11]);
        record.fuel = fieldSetFlags()[12] ? this.fuel : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.gearBoxId = fieldSetFlags()[13] ? this.gearBoxId : (java.lang.Integer) defaultValue(fields()[13]);
        record.gearBox = fieldSetFlags()[14] ? this.gearBox : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.driveId = fieldSetFlags()[15] ? this.driveId : (java.lang.Integer) defaultValue(fields()[15]);
        record.drive = fieldSetFlags()[16] ? this.drive : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.location = fieldSetFlags()[17] ? this.location : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.region = fieldSetFlags()[18] ? this.region : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.race = fieldSetFlags()[19] ? this.race : (java.lang.CharSequence) defaultValue(fields()[19]);
        record.raceInt = fieldSetFlags()[20] ? this.raceInt : (java.lang.Integer) defaultValue(fields()[20]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CarAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<CarAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CarAvro>
    READER$ = (org.apache.avro.io.DatumReader<CarAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.addDate);

    out.writeInt(this.brandId);

    out.writeString(this.brand);

    out.writeInt(this.modelId);

    out.writeString(this.model);

    out.writeString(this.title);

    if (this.desc == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.desc);
    }

    out.writeInt(this.priceUsd);

    out.writeInt(this.year);

    out.writeString(this.link);

    out.writeInt(this.fuelId);

    out.writeString(this.fuel);

    if (this.gearBoxId == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeInt(this.gearBoxId);
    }

    if (this.gearBox == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.gearBox);
    }

    if (this.driveId == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeInt(this.driveId);
    }

    if (this.drive == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.drive);
    }

    out.writeString(this.location);

    out.writeString(this.region);

    if (this.race == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.race);
    }

    if (this.raceInt == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeInt(this.raceInt);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.addDate = in.readString(this.addDate instanceof Utf8 ? (Utf8)this.addDate : null);

      this.brandId = in.readInt();

      this.brand = in.readString(this.brand instanceof Utf8 ? (Utf8)this.brand : null);

      this.modelId = in.readInt();

      this.model = in.readString(this.model instanceof Utf8 ? (Utf8)this.model : null);

      this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);

      if (in.readIndex() != 0) {
        in.readNull();
        this.desc = null;
      } else {
        this.desc = in.readString(this.desc instanceof Utf8 ? (Utf8)this.desc : null);
      }

      this.priceUsd = in.readInt();

      this.year = in.readInt();

      this.link = in.readString(this.link instanceof Utf8 ? (Utf8)this.link : null);

      this.fuelId = in.readInt();

      this.fuel = in.readString(this.fuel instanceof Utf8 ? (Utf8)this.fuel : null);

      if (in.readIndex() != 0) {
        in.readNull();
        this.gearBoxId = null;
      } else {
        this.gearBoxId = in.readInt();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.gearBox = null;
      } else {
        this.gearBox = in.readString(this.gearBox instanceof Utf8 ? (Utf8)this.gearBox : null);
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.driveId = null;
      } else {
        this.driveId = in.readInt();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.drive = null;
      } else {
        this.drive = in.readString(this.drive instanceof Utf8 ? (Utf8)this.drive : null);
      }

      this.location = in.readString(this.location instanceof Utf8 ? (Utf8)this.location : null);

      this.region = in.readString(this.region instanceof Utf8 ? (Utf8)this.region : null);

      if (in.readIndex() != 0) {
        in.readNull();
        this.race = null;
      } else {
        this.race = in.readString(this.race instanceof Utf8 ? (Utf8)this.race : null);
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.raceInt = null;
      } else {
        this.raceInt = in.readInt();
      }

    } else {
      for (int i = 0; i < 21; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.addDate = in.readString(this.addDate instanceof Utf8 ? (Utf8)this.addDate : null);
          break;

        case 2:
          this.brandId = in.readInt();
          break;

        case 3:
          this.brand = in.readString(this.brand instanceof Utf8 ? (Utf8)this.brand : null);
          break;

        case 4:
          this.modelId = in.readInt();
          break;

        case 5:
          this.model = in.readString(this.model instanceof Utf8 ? (Utf8)this.model : null);
          break;

        case 6:
          this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
          break;

        case 7:
          if (in.readIndex() != 0) {
            in.readNull();
            this.desc = null;
          } else {
            this.desc = in.readString(this.desc instanceof Utf8 ? (Utf8)this.desc : null);
          }
          break;

        case 8:
          this.priceUsd = in.readInt();
          break;

        case 9:
          this.year = in.readInt();
          break;

        case 10:
          this.link = in.readString(this.link instanceof Utf8 ? (Utf8)this.link : null);
          break;

        case 11:
          this.fuelId = in.readInt();
          break;

        case 12:
          this.fuel = in.readString(this.fuel instanceof Utf8 ? (Utf8)this.fuel : null);
          break;

        case 13:
          if (in.readIndex() != 0) {
            in.readNull();
            this.gearBoxId = null;
          } else {
            this.gearBoxId = in.readInt();
          }
          break;

        case 14:
          if (in.readIndex() != 0) {
            in.readNull();
            this.gearBox = null;
          } else {
            this.gearBox = in.readString(this.gearBox instanceof Utf8 ? (Utf8)this.gearBox : null);
          }
          break;

        case 15:
          if (in.readIndex() != 0) {
            in.readNull();
            this.driveId = null;
          } else {
            this.driveId = in.readInt();
          }
          break;

        case 16:
          if (in.readIndex() != 0) {
            in.readNull();
            this.drive = null;
          } else {
            this.drive = in.readString(this.drive instanceof Utf8 ? (Utf8)this.drive : null);
          }
          break;

        case 17:
          this.location = in.readString(this.location instanceof Utf8 ? (Utf8)this.location : null);
          break;

        case 18:
          this.region = in.readString(this.region instanceof Utf8 ? (Utf8)this.region : null);
          break;

        case 19:
          if (in.readIndex() != 0) {
            in.readNull();
            this.race = null;
          } else {
            this.race = in.readString(this.race instanceof Utf8 ? (Utf8)this.race : null);
          }
          break;

        case 20:
          if (in.readIndex() != 0) {
            in.readNull();
            this.raceInt = null;
          } else {
            this.raceInt = in.readInt();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










